### ISSUE TITLE
Multiple lines not displaying properly in output

### ISSUE THREAD

**Issue by rcrdlbl** [learn-co-curriculum/python-dictionaries-readme#4]
In the python dictionaries lab there's this issue where not all of the outputs of a snippet of code will display. Not sure if this is a bug or not but if it isn't then I feel like it's kind of a usability issue considering that the comments imply two outputs are supposed to be showing up.

![learnco issue 2](https://user-images.githubusercontent.com/40729534/42140524-b54d70ac-7d6e-11e8-9616-28abbb1dfe56.png)
![learnco issue 1](https://user-images.githubusercontent.com/40729534/42140526-b55c2e08-7d6e-11e8-83af-b56f06a7d861.png)

**Comment by LoreDirick** [comment]
Hi @rcrdlbl this is a known thing in Jupyter Notebooks in general.
You can use print() to make python explicitly print anything not executed last, in your case:

```
print(pyeongchang_values)
type(pyeongchang_values)
```
or

 ```
print(pyeongchang_values)
print(type(pyeongchang_values))
```

Both will work.
