### ISSUE TITLE
Issue 31 

### ISSUE THREAD

**Issue by JatanShah1** [learn-co-curriculum/python-dictionaries-readme#6]
Hi
With Input 30 creators=['David Crane','Marta Kauffman']
When i am trying to recall this list in the dictionary 
In Input 31 friends['creators'] I am seeing this error. 

KeyErrorTraceback (most recent call last)
<ipython-input-31-8f2f50f5f30a> in <module>()
----> 1 friends['creators']

KeyError: 'creators'

Am i missing something? Thanks

**Comment by mas16** [comment]
Hi JatanShah1, you can seek help by using the ask a question feature in Learn. These github issues are reserved for technical problems with the lesson/lab. Thanks and good luck!
